### PR TITLE
Updated README to add link to bioRxiv manuscript and Dryad database.

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
Odd:
https://travis-ci.org/choderalab/ensembler/builds/71865045#L322
```
Error: could not find environment: 2.7
```

**Comment by danielparton** [comment]
The problem with the Travis test here is that the Modeller license key, which I had stored using an encrypted environment variable, is not being picked up.

Apparently encrypted environment variables are not available to pull requests from forks due to the security risk of adding unknown code:
http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by danielparton** [comment]
The Travis docs just recommend disabling tests which require secure environment variables:
http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

I could disable any Modeller-dependent tests for PRs. That seems like the simplest thing to do for now. Anyone else have advice here?

**Comment by jchodera** [comment]
> I could disable any Modeller-dependent tests for PRs. That seems like the simplest thing to do for now.

Sounds reasonable!  Go ahead and merge this and tackle that in a separate PR?

**Comment by danielparton** [comment]
K, will do. Thanks

**Pull request merged**
