### PR TITLE
Rosetta usage specifics added to docs

### PR DESCRIPTION
**Pull request by sonyahanson**
Rosetta usage specifics added to docs, as per #61.

### CODE REVIEW

**Comment by jchodera** [comment]
Looks good!

Travis is broken for an unrelated reason. I can fix that.

**Comment by sonyahanson** [comment]
@steven-albanese just noticed this was never merged.

**Comment by rafwiewiora** [comment]
you guys want to merge this in?

**Comment by jchodera** [comment]
I'll merge it since it's just a docs change.

**Pull request merged**
